CadastroAnuncio/Models/CadastroAnuncioModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CadastroAnuncio.Models
{
    public class CadastroAnuncioModel
    {
        public int Id { get; set; }
        public string NomeAnuncio { get; set; }
        public string NomeCliente { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime?  DataInicio { get ; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? DataTermino { get; set;}
        public double InvestimentoDia { get; set; }
        public double ValorTotalInvestido { get; set; }
        public double? QtdMaxVizualizacao { get; set; }
        public double? QtdMaxClique { get; set; }
        public double? QtdMaxCompartilhamento { get; set; }
        public string FiltroNomeCliente { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? FIltroDataTermino { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? FiltroDataInicio { get; set; }

    }
}

CadastroAnuncio/Controllers/CadastroAnuncioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CadastroAnuncio.BancoDados;
using CadastroAnuncio.Models;
using CadastroAnuncio.RegraDeNegocio;
using Rotativa;

namespace CadastroAnuncio.Controllers
{
    public class CadastroAnuncioController : Controller
    {
        private CadastroAnuncioContexto db = new CadastroAnuncioContexto();

        // GET: CadastroAnuncio
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult Listar(int pagina = 1, int registros = 5)
        {
            var anuncios = db.CadastroAnuncio;
            var anunciosPaginado = anuncios.OrderBy(x => x.NomeAnuncio).Skip((pagina - 1) * registros).Take(registros);
            int quantidadePaginasAnuncios = anunciosPaginado.Count();
            return PartialView("_Listar", anunciosPaginado.ToList());
        }
        public ActionResult Filtro()
        {
            return View();
        }

        public ActionResult Relatorio()
        {
            return new ViewAsPdf(db.CadastroAnuncio.ToList());
        }

        // GET: CadastroAnuncio/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CadastroAnuncioModel cadastroAnuncioModel = db.CadastroAnuncio.Find(id);
            if (cadastroAnuncioModel == null)
            {
                return HttpNotFound();
            }
            return View(cadastroAnuncioModel);
        }

        // GET: CadastroAnuncio/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CadastroAnuncio/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NomeAnuncio,NomeCliente,DataInicio,DataTermino,InvestimentoDia,ValorTotalInvestido,QtdMaxVizualizacao,QtdMaxClique,QtdMaxCompartilhamento")] CadastroAnuncioModel cadastroAnuncioModel)
        {
            if (ModelState.IsValid)
            {
               
                if (cadastroAnuncioModel.DataInicio < DateTime.Now.Date)
                {
                    TempData["mensagemErroDataInicio"] = "Não é possível cadastrar data inferior a de hoje";
                    return View(cadastroAnuncioModel);
                }
                if (cadastroAnuncioModel.DataTermino < cadastroAnuncioModel.DataInicio)
                {
                    TempData["mensagemErroDataFIm"] = "Não é possível cadastrar a Data de Termino menor que a de início";
                    return View(cadastroAnuncioModel);
                }
                var qtdViewDia = (int)QtdViewDia.GetQtdViewDia(cadastroAnuncioModel.InvestimentoDia);
                var tempoAnuncio = TempoDoAnuncio.GetTempoDoAnuncio(cadastroAnuncioModel.DataInicio, cadastroAnuncioModel.DataTermino);
                cadastroAnuncioModel.QtdMaxClique = qtdViewDia * tempoAnuncio / (int)VariavelFixa.ViewClique;
                var investimentoDia = cadastroAnuncioModel.InvestimentoDia;
                var compartilhamentos = TotalCompartilhamento.GetCompartilhamentos(cadastroAnuncioModel.QtdMaxClique, VariavelFixa.CliqueCompartilhamento);
                var tempoDoAnuncio = TempoDoAnuncio.GetTempoDoAnuncio(cadastroAnuncioModel.DataInicio, cadastroAnuncioModel.DataTermino);
                var viewAdicionais = ViewAdicional.GetViewAdicionais(compartilhamentos);
                cadastroAnuncioModel.ValorTotalInvestido = investimentoDia * tempoAnuncio; 
                cadastroAnuncioModel.QtdMaxVizualizacao = qtdViewDia * tempoDoAnuncio + viewAdicionais;
                cadastroAnuncioModel.QtdMaxCompartilhamento = compartilhamentos;
                db.CadastroAnuncio.Add(cadastroAnuncioModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }                                                                   

            return View(cadastroAnuncioModel);
        }

        // GET: CadastroAnuncio/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CadastroAnuncioModel cadastroAnuncioModel = db.CadastroAnuncio.Find(id);
            if (cadastroAnuncioModel == null)
            {
                return HttpNotFound();
            }
            //var dataFormatada = cadastroAnuncioModel.
            return View(cadastroAnuncioModel);
        }

        // POST: CadastroAnuncio/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NomeAnuncio,NomeCliente,DataInicio,DataTermino,InvestimentoDia,ValorTotalInvestido,QtdMaxVizualizacao,QtdMaxClique,QtdMaxCompartilhamento")] CadastroAnuncioModel cadastroAnuncioModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cadastroAnuncioModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cadastroAnuncioModel);
        }

        // GET: CadastroAnuncio/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CadastroAnuncioModel cadastroAnuncioModel = db.CadastroAnuncio.Find(id);
            if (cadastroAnuncioModel == null)
            {
                return HttpNotFound();
            }
            return View(cadastroAnuncioModel);
        }

        // POST: CadastroAnuncio/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CadastroAnuncioModel cadastroAnuncioModel = db.CadastroAnuncio.Find(id);
            db.CadastroAnuncio.Remove(cadastroAnuncioModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CadastroAnuncio/Views/CadastroAnuncio/Create.cshtml
@model CadastroAnuncio.Models.CadastroAnuncioModel

@{
    ViewBag.Title = "Create";
}

<h2>Cadastro Anúncio</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label id="label-nome-anuncio" for="nome-Anuncio" mas>Nome do Anúncio<span class="text-danger">*</span></label>
                    @Html.EditorFor(model => model.NomeAnuncio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NomeAnuncio, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label id="label-nome-anuncio" for="nome-Anuncio" mas>Nome do Cliente<span class="text-danger">*</span></label>
                    @Html.EditorFor(model => model.NomeCliente, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NomeCliente, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label id="label-nome-anuncio" for="nome-Anuncio" mas>Data do Início<span class="text-danger">*</span></label>
                    @Html.EditorFor(model => model.DataInicio, new { htmlAttributes = new { @class = "form-control", id = "data-inicio" } })
                    @if (TempData["mensagemErroDataInicio"] != null)
                    {<div class="field-error"><div class="text-danger"> @TempData["mensagemErroDataInicio"]</div> </div>}
                    @Html.ValidationMessageFor(model => model.DataInicio, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label id="label-nome-anuncio" for="nome-Anuncio" mas>Data do Fim<span class="text-danger">*</span></label>
                    @Html.EditorFor(model => model.DataTermino, new { htmlAttributes = new { @class = "form-control", id = "data-termino" } })
                    @if (TempData["mensagemErroDataFim"] != null)
                    {<div class="field-error"><div class="text-danger"> @TempData["mensagemErroDataFim"]</div> </div>}
                    @Html.ValidationMessageFor(model => model.DataTermino, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <label id="label-nome-anuncio" for="nome-Anuncio" mas>Investimento Diário<span class="text-danger">*</span></label>
                    @Html.EditorFor(model => model.InvestimentoDia, new { htmlAttributes = new { @class = "form-control", id = "valor-investido" } })
                    @Html.ValidationMessageFor(model => model.InvestimentoDia, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group text-right">
            <div class="col-md-offset-2 col-md-10">
                <div class="btn btn-default">
                    @Html.ActionLink("Voltar", "Index")
                </div>
                <input type="submit" value="Criar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>

</div>
@section scripts {
    <script src="~/Scripts/jquery.mask.min.js"></script>
    <script src="~/Scripts/CadastroAnuncio/MaskCadastroAnuncio.js"></script>

}

CadastroAnuncio/Views/CadastroAnuncio/Delete.cshtml
@model CadastroAnuncio.Models.CadastroAnuncioModel

@{
    ViewBag.Title = "Delete";
}

<h2>Apagar</h2>

<h3>Deseja Realmente Apagar o Anúncio?</h3>
<div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color text-right">
            <div class="btn btn-default">
                @Html.ActionLink("Voltar", "Index")
            </div>
            <input type="submit" value="Apagar" class="btn btn-danger" />
        </div>
    }
</div>

CadastroAnuncio/Views/CadastroAnuncio/Edit.cshtml
@model CadastroAnuncio.Models.CadastroAnuncioModel

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label id="label-nome-anuncio" mas>Nome do Anúncio<span class="text-danger">*</span></label>
                    @Html.EditorFor(model => model.NomeAnuncio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NomeAnuncio, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label id="label-nome-anuncio" mas>Nome do Cliente<span class="text-danger">*</span></label>
                    @Html.EditorFor(model => model.NomeCliente, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NomeCliente, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label id="label-nome-anuncio" mas>Data do Início<span class="text-danger">*</span></label>
                    @Html.EditorFor(model => model.DataInicio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DataInicio, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label id="label-nome-anuncio" mas>Data do Fim<span class="text-danger">*</span></label>
                    @Html.EditorFor(model => model.DataTermino, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DataTermino, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <label id="label-nome-anuncio" mas>Investimento Diário<span class="text-danger">*</span></label>
                    @Html.EditorFor(model => model.InvestimentoDia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.InvestimentoDia, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group text-right">
            <div class="col-md-offset-2 col-md-10">
                <div class="btn btn-default">
                    @Html.ActionLink("Voltar", "Index")
                </div>
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

CadastroAnuncio/Views/CadastroAnuncio/Filtro.cshtml
@model CadastroAnuncio.Models.CadastroAnuncioModel
@{
    ViewBag.Title = "Filtro";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="row">
    <div class="col-sm-4">
        <div class="form-group">
            <label id="label-nome-anuncio" for="nome-Anuncio" mas>Nome do Cliente<span class="text-danger">*</span></label>
            @Html.EditorFor(model => model.FiltroNomeCliente, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FiltroNomeCliente, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group">
            <label id="label-nome-anuncio" for="nome-Anuncio" mas>Data do Início<span class="text-danger">*</span></label>
            @Html.EditorFor(model => model.FiltroDataInicio, new { htmlAttributes = new { @class = "form-control" } })
            @if (TempData["mensagemErroDataInicio"] != null)
            {<div class="field-error"><div class="text-danger"> @TempData["mensagemErroDataInicio"]</div> </div>}
            @Html.ValidationMessageFor(model => model.FiltroDataInicio, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group">
            <label id="label-nome-anuncio" for="nome-Anuncio" mas>Data do Fim<span class="text-danger">*</span></label>
            @Html.EditorFor(model => model.FIltroDataTermino, new { htmlAttributes = new { @class = "form-control" } })
            @if (TempData["mensagemErroDataFim"] != null)
            {<div class="field-error"><div class="text-danger"> @TempData["mensagemErroDataFim"]</div> </div>}
            @Html.ValidationMessageFor(model => model.FIltroDataTermino, "", new { @class = "text-danger" })
        </div>
    </div>
</div>
<div class="col-sm-offser-2 col sm-10">
    @Html.ActionLink("Gerar Relatório", "Relatorio")

</div>
}

CadastroAnuncio/Views/CadastroAnuncio/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Anúncios</h2>

<div class="row">
    <div class="text-right">
        <div class="btn btn-default">
            @Html.ActionLink("Gerar Relatório", "Relatorio", new { @class = "btn btn-primary" })

            

        </div>
        <div class="btn btn-default">
            @Html.ActionLink("Novo cadastro", "Create")
        </div>

    </div>
</div>


<div id="listagemDeAnuncios"></div>


@section scripts{
    <script type="text/javascript">

        $(document).ready(configurarController);
        function configurarController() {
            $("#listagemDeAnuncios").load("@Url.Action("Listar")");
        }
        var pagina = 1;

        function paginar(valor) {
                var paginaNova = pagina + valor;
                $("#listagemDeAnuncios").load("@Url.Action("Listar")", { pagina: paginaNova });
                pagina = paginaNova;
        }
    </script>
}

CadastroAnuncio/Views/CadastroAnuncio/Relatorio.cshtml
@model IEnumerable<CadastroAnuncio.Models.CadastroAnuncioModel>

@{
    ViewBag.Title = "Relatorio";
    Layout = "";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport"content="width=device-width"/>
    <title>Cadastro de Anúncios</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="col-md-12 text-center">
        <h3>Cadastro Anúncios</h3>
        <table class="table">
            <tr>
                <th>
                    Nome Cliente
                </th>

                <th>
                   Total Investido
                </th>
                <th>
                   Visualizações
                </th>
                <th>
                    Cliques
                </th>
                <th>
                    Compartilhamentos
                </th>

            </tr>

            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.NomeCliente)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ValorTotalInvestido)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.QtdMaxVizualizacao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.QtdMaxClique)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.QtdMaxCompartilhamento)
                    </td>

                </tr>
            }

        </table>
    </div>
</body>
</html>

CadastroAnuncio/Views/CadastroAnuncio/_Listar.cshtml
@model IEnumerable<CadastroAnuncio.Models.CadastroAnuncioModel>
@{
    ViewBag.Title = "Listar";
}
<table class="table">
    <tr>
        <th>
            Anúncio
        </th>
        <th>
            Cliente
        </th>
        <th>
            Início
        </th>
        <th>
            Término
        </th>
        <th>
            Valor Investido Dia
        </th>
        <th>
            Ação
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomeAnuncio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomeCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataTermino)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InvestimentoDia)
            </td>

            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" }) 
                @Html.ActionLink("Apagar", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>
<div class="text-right">
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item" id="item-anterior-fornecedores">
                <a class="page-link" href="#" onclick="paginar(-1)">Anterior</a>
            </li>
            <li class="page-item" id="item-proximo-fornecedores">
                <a class="page-link" href="#" onclick="paginar(1)">Próximo</a>
            </li>
        </ul>
    </nav>
</div>

CadastroAnuncio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cadastro Anúncio", "Index", "CadastroAnuncio", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Anúncios", "Index", "CadastroAnuncio")</li>
                    <li>@Html.ActionLink("Relatório", "Relatorio", "CadastroAnuncio")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>